### ISSUE TITLE
[FEAT] Add support for RX-V3900

### ISSUE THREAD

**Issue by juw2** [lucasvdh/com.yamaha.receiver#16]
### Describe the bug
When trying to add my Yamaha RX-V3900 using the beta from the app store, and add the IP address I get {"message":"Cannot read property 'toString' of undefined"}.

### Expected Behavior
Receiver to be added to homey

### Actual Behavior
Errors out with abow error

### Steps to Reproduce the Problem

  1. Include Yamaha RX-V3900
  1.
  1.

**Comment by juw2** [comment]
Hi.
Tried version 1.0.2 now and when including the receiver I now get:
{"message":"Non-whitespace before first tag.\nLine:0\nColumn: 1\nChar: E"}

**Comment by juw2** [comment]
[Yamaha RX-V3900 error v1.0.2.txt](https://github.com/lucasvdh/com.yamaha.receiver/files/4791094/Yamaha.RX-V3900.error.v1.0.2.txt)
Not sure if it will help but added the error shown from Node.js command line window.

**Comment by juw2** [comment]
Also, autodiscovery doesn't work as you can see in the text file. I have to add the IP manually.

**Comment by lucasvdh** [comment]
Hi @juw2 the `Non-whitespace before first tag` error was an issue with the app not handling an error response correctly and has been resolved in version `1.1.x`. The message should've been something like "Could not fetch receiver name".

The underlying issue is probably not resolved yet. I will investigate the issue somewhere next week and will ask any question I have for you here.

**Comment by lucasvdh** [comment]
Could you maybe check if you get a response from http://192.168.1.74:8080/MediaRenderer/desc.xml

If so, could you save the response and share it here?

**Comment by juw2** [comment]
Hi Lucas ant thanks for your effort.

Port 8080 doesn’t work but 80 do.
Response from http://192.168.1.74:80/MediaRenderer/desc.xml

<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:ms="urn:microsoft-com:wmc-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device ms:X_MS_SupportsWMDRM="true">
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<friendlyName>RX-V3900</friendlyName>
<manufacturer>YAMAHA CORPORATION</manufacturer>
<manufacturerURL>http://www.global.yamaha.com/</manufacturerURL>
<modelDescription>Network Receiver</modelDescription>
<modelName>RX-V3900</modelName>
<modelNumber>3900</modelNumber>
<modelURL>http://www.global.yamaha.com/products/av/index.html</modelURL>
<serialNumber>0C76E4D3</serialNumber>
<UDN>uuid:26237000-9894-11db-9976-00a0de4c72d6</UDN>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/Icons/48x48.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<SCPDURL>/RenderingControl/desc.xml</SCPDURL>
<controlURL>/RenderingControl/ctrl</controlURL>
<eventSubURL>/RenderingControl/event</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<SCPDURL>/ConnectionManager/desc.xml</SCPDURL>
<controlURL>/ConnectionManager/ctrl</controlURL>
<eventSubURL>/ConnectionManager/event</eventSubURL>
</service>
<service>
<serviceType>urn:yamaha-com:service:YamahaRemoteControl:2</serviceType>
<serviceId>urn:yamaha-com:serviceId:YamahaRemoteControl</serviceId>
<SCPDURL>/YamahaRemoteControl/desc.xml</SCPDURL>
<controlURL>/YamahaRemoteControl/ctrl</controlURL>
<eventSubURL>/YamahaRemoteControl/event</eventSubURL>
</service>
</serviceList>
<presentationURL>http://192.168.1.74/</presentationURL>
</device>
</root>


With version 1.1.1 I get a long error when trying to include it.
{"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:237:11)\n    at IncomingMessage.emit (events.js:323:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"url":"http://192.168.1.74:80/YamahaRemoteControl/ctrl","method":"post","data":"<YAMAHA_AV cmd=\"GET\"><System><Misc><Network><Network_Name>GetParam</Network_Name></Network></Misc></System></YAMAHA_AV>","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/0.19.0","Content-Length":119},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}


When googling on my issue, I found this:
https://community.openhab.org/t/yamahareceiver-zone-discovery-not-working-with-rx-v3900/38350
I know it’s another system but they talk about differences with RX-V3900.

Could that be why it’s not working?

Br
Jonas

**Comment by lucasvdh** [comment]
Thanks for all the info @juw2 this is very helpful.

At least now I know why your device doesn't show up in auto discovery. The auto discovery of the Yamaha AV Receiver looks for `<modelDescription>AV Receiver</modelDescription>` and your device is apparenly Network Receiver (`<modelDescription>Network Receiver</modelDescription>`).

Also, according to the YamahaRemoteControl documentation for AV Receivers the `/MediaRenderer/desc.xml` should contain a `<yamaha:X_device>` root element which I do not see in this case. So it might be that this is a different version of the YamahaRemoteControl api. The thread on community.openhab.org seems to be saying the same.

I will look into what changes are required to support this model. Just to be sure, can you please share the content of the `/YamahaRemoteControl/desc.xml` here?
[http://192.168.1.74/YamahaRemoteControl/desc.xml](http://192.168.1.74/YamahaRemoteControl/desc.xml)

To manage expectations: I'm currently working on fixing some core issues regarding multiple zone support in MusicCast devices. I will start on this issue after I've completed those.

I'll post any progress I make, or when there's a new version for you to test, here.

**Comment by juw2** [comment]
The answer is to http://192.168.1.74/YamahaRemoteControl/desc.xml is:

<scpd>
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
</scpd>

Br
Jonas

**Comment by lucasvdh** [comment]
For my own reference:
https://github.com/openhab/openhab-addons/pull/3264

**Comment by juw2** [comment]
Hi Lucas.
See my marking below.
When googeling, it seems like that section only exists on network receivers that has MusicCast built in. Mine doesn’t. Could that be the case?
In that case maybe there should be another way of discovering a receiver.

Br
Jonas

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

Från: Lucas van der Have<mailto:notifications@github.com>
Skickat: den 18 juni 2020 16:28
Till: lucasvdh/com.yamaha.receiver<mailto:com.yamaha.receiver@noreply.github.com>
Kopia: juw2<mailto:juw2@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Ämne: Re: [lucasvdh/com.yamaha.receiver] Yamaha RX-V3900 returning bad request 400 (#16)


Thanks for all the info @juw2<https://github.com/juw2> this is very helpful.

At least now I know why your device doesn't show up in auto discovery. The auto discovery of the Yamaha AV Receiver looks for <modelDescription>AV Receiver</modelDescription> and your device is apparenly Network Receiver (<modelDescription>Network Receiver</modelDescription>).

Also, according to the YamahaRemoteControl documentation for AV Receivers the /MediaRenderer/desc.xml should contain a <yamaha:X_device> root element which I do not see in this case. So it might be that this is a different version of the YamahaRemoteControl api. The thread on community.openhab.org seems to be saying the same.

I will look into what changes are required to support this model. Just to be sure, can you please share the content of the /YamahaRemoteControl/desc.xml here?
http://192.168.1.74/YamahaRemoteControl/desc.xml

To manage expectations: I'm currently working on fixing some core issues regarding multiple zone support in MusicCast devices. I will start on this issue after I've completed those.

I'll post any progress I make, or when there's a new version for you to test, here.
