### ISSUE TITLE
[BUG] Previous MusicCast driver crash

### ISSUE THREAD

**Issue by lucasvdh** [lucasvdh/com.yamaha.receiver#5]
### Describe the bug
Previous MusicCast driver crashes on debug log

### Expected Behavior
This should not happen

### Steps to Reproduce the Problem
  1. Empty `data` object on log

### Stack trace
```text
 /drivers/musiccast/driver.js:199
                Homey.log('[' + device_data.name + '] mute info:', data.mute);
                                                                        ^

TypeError: Cannot read property 'mute' of undefined
    at /drivers/musiccast/driver.js:199:73
    at Request._callback (/drivers/musiccast/driver.js:262:13)
    at self.callback (/node_modules/request/request.js:200:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/node_modules/request/request.js:826:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
```

**Comment by lucasvdh** [comment]
Newer version was published
